### PR TITLE
Quest saves refactor

### PR DESCRIPTION
**Pull request by lellis0406**
# Description

Cleaned up and refactored various Quest and SaveHandler implementations.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Completed various in game actions and saved/loaded in various configurations to ensure proper functionality.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jt-09 — APPROVED** [review]
looks good. I like the singleton idea for the SaveHandler. Too bad HiddenQuests could not be implemented.

**Review by TarushiG — APPROVED** [review]
Looks good & love the improvement in modularity!

**Comment by Slothlesss** [comment]
Looks good. The quest system tracks player's progress well.

**Review by Slothlesss — APPROVED** [review]
Looks good. The quest system tracks player's progress well.

**Pull request merged**
