### PR TITLE
Intro Story

### PR DESCRIPTION
**Pull request by reonse**
Included intro story so that it would occur after selecting an animal then clicking the ready button. Goes through each 'slide' of the story by clicking next or back. After reaching the final slide, clicking next will bring you to the loading screen then main game. Most changes were just the addition of new classes and adjusting which screens were called to alter the flow of screens (from selection screen -> loading screen -> main game screen, then now selection screen -> story screen -> loading screen -> main game screen).
Images were made by a member of team 6.
I'm from team 9, however, my task is independent from them.
However, everything seems to be functional and I'd like to merge it to main so that I can avoid any merge conflicts in the future.

### CODE REVIEW

**Review by lhick2108 — APPROVED** [review]
Everything here seems great, more docstrings would be preferable and maybe a test or two.

**Review by lhick2108 — APPROVED** [review]
Showing that I viewed the files woops :)

**Review by jaden-z-fng — APPROVED** [review]
Every animal has the same beginning backstory, but I'm guessing that's for future sprints

**Comment by reonse** [comment]
> Every animal has the same beginning backstory, but I'm guessing that's for future sprints

That's right, the classes and method calls will be modified to account for the animal selected in future sprints.

**Pull request merged**
