### PR TITLE
[Team 1] Animal stats, sounds and movement

### PR DESCRIPTION
**Pull request by AndreBissell**
-Added tests for player sounds
-Displayed player stats in animal selection screens
-Displayed stats in game with overlay
-Introduces different movement speeds for each animal

### CODE REVIEW

**Review by ishusharma13 — APPROVED** [review]
looks good! code looks clean

**Review by JackMccabe2 — APPROVED** [review]
All changes appear to be valid. Written in solid coding practices and no errors.

**Comment by sneha-zazen** [comment]
Looks good 👍

**Review by sneha-zazen — APPROVED** [review]

**Comment by falgonn** [comment]
merging commits to main

**Pull request merged**
