### PR TITLE
BUG FIX: Game crashes as 'saves/endgameStats.json' does not exist

### PR DESCRIPTION
**Pull request by phurinjeffy**
# Integrate Stat Saving

Fixed a bug, when you first run the game it crashes, StatManager seems to be throwing a java.lang.NullPointerException upon loading into game, as it's trying to read from a file 'saves/endgameStats.json' which does not exist yet. Required to integrate saving of stats with the gamestate SaveHandler

## To reproduce the error:
- Delete endgameStats.json from /saves
- Start game
- Load into game

### CODE REVIEW

**Review by nownver — APPROVED** [review]
Good job!, thanks for fixing it.

**Review by paulpleela — APPROVED** [review]

**Review by praneetdhoolia — CHANGES_REQUESTED** [review]
Seems like there are a few issues with compilation, please fix.

**Comment by phurinjeffy** [comment]
> Seems like there are a few issues with compilation, please fix.

Got it

**Review by nownver — APPROVED** [review]
Looks good, thank for fixing this

**Review by paulpleela — APPROVED** [review]
Looks like its working now

**Pull request merged**
