### PR TITLE
8 maptab

### PR DESCRIPTION
**Pull request by BenGhahramaniUQ**
# Description
Merged the changes from the 8-map branch into main, which includes updates for the map tab feature, as well as conflict resolutions. Pressing M in game will toggle on/off a full view of the map with respect to player and landmark position. 

Closes (#358)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I ran manual tests to verify that the minimap feature works as expected when toggling the map on and off. I also ensured that there were no conflicts in merging the branch with main and verified that the game continues to run without errors.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BenGhahramaniUQ** [comment]
@mitsudz 
In screens/MainGameScreen, pressing 'M' will toggle the map, opening a picture representation of the map with player and landmark icon images over them.

**Review by mitsudz — CHANGES_REQUESTED** [review]
There's a few issues I think with this PR: 

Firstly see how virtually all other UI components are made - to fit in with the current format of the game you should have the map be a component attached to the game (seems like based on the map it should be attached to the terrain or forest game area or the player?) and you really shouldn't be changing the MainGameScreen class this much. 

Next, when pressing the X in the top right it seems to sometimes transmit this click down to the Exit button below it which causes you to exit the game.

Finally - this isn't so relevant but I'm not really a fan of the styling of the map and how it fits in with the rest of the game. That's just my personal opinion though and others/you may disagree which is fine.

**Comment by BenGhahramaniUQ** [comment]
@mitsudz 
Thanks for the feedback, isolated the code into /components/gamearea/maptabcomponent. Rotated x to top left to avoid double click. Please see (#531), closing this one as I opened a new branch to fix it up. 
I understand the images look barebones and do not fully align with the rest of the game, this is to be improved in the future.

**Review by LucasRyall — CHANGES_REQUESTED** [review]
While there is nothing bad about how you've implemented the change (aside from there being no javadocs), the map doesn't actually display any information about the position of anything. I would like to see this changed before it gets merged into main.

**Comment by BenGhahramaniUQ** [comment]
@LucasRyall 
Hey, the dimensions of the map was off by some factor which I think made it look like player position was not updating. This is fixed so updated positions should be easier to see. Also added appropriate documentation with a more appropriate map view.

**Review by LucasRyall — CHANGES_REQUESTED** [review]
Some style changes that need to be made, and code that can be deleted because it isn't being used. Also can you make the backgrounds transparent for the icons used on the map, rather than the checkered backgrounds.

**Review by LucasRyall — APPROVED** [review]
Thanks for addressing my messages.

**Review by phurinjeffy — APPROVED** [review]
looks good to me

**Pull request merged**
