### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by LucasRyall**
# Description

Aim of this pull request is to reduce duplicated code and remove issues that sonar cloud has with the code. I believe no functional changes have been made, and everything should work as before.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Nothing functional should be changed, but to double check I would run around the game everyone once in a while to check that everything still worked and that no behaviour had changed.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by BaileyS03** [comment]
Considering you have changed some of my teams code without us knowing please see the PR I made for style on my teams code. Some of this overlaps, and I started this without knowledge of a collaboration ticket. Happy for both of us to do it but I’m also gonna claim my work on my teams feature :)
(https://github.com/UQcsse3200/2024-studio-2/pull/534)

**Comment by LucasRyall** [comment]
> Considering you have changed some of my teams code without us knowing please see the PR I made for style on my teams code. Some of this overlaps, and I started this without knowledge of a collaboration ticket. Happy for both of us to do it but I’m also gonna claim my work on my teams feature :) (#534)

Yea no worries, If you would like I can wait to push this until you have pushed your code, and merge it with you changes getting preference over mine given its your groups feature.

**Comment by BaileyS03** [comment]
> > Considering you have changed some of my teams code without us knowing please see the PR I made for style on my teams code. Some of this overlaps, and I started this without knowledge of a collaboration ticket. Happy for both of us to do it but I’m also gonna claim my work on my teams feature :) (#534)
> 
> Yea no worries, If you would like I can wait to push this until you have pushed your code, and merge it with you changes getting preference over mine given its your groups feature.


no stress it’ll be the same sort of changes so an easy merge anyways

**Review by BaileyS03 — APPROVED** [review]
Looks good to me, and game play is as expected. Style looks significantly better thank you.

**Review by mitsudz — APPROVED** [review]
Looks good, can be merged as soon as merge conflicts are resolved appropriately.

**Pull request merged**
