### PR TITLE
9/ Post Combat

### PR DESCRIPTION
**Pull request by Ajay-Datt**
#### 1. **Game Stats Tracking and Display**
- **Stat Class**: Introduced a class to handle tracking in-game stats like item collection, enemy defeats, and player progress. Supports operations such as setting, incrementing, and decrementing stats.
- **StatDisplay**: A UI component that shows detailed stats (items, enemies, player) in a tabbed interface after the final boss is defeated. Includes hover effects for better user experience.
- **StatManager**: Manages event listeners to track player stats and update them dynamically based on game events (e.g., item collection, enemy defeat).
- **StatSaveManager**: Implements save/load functionality for stats, ensuring persistence across sessions.

#### 2. **Combat Win Handling and Screen Transition**
- **Combat Win Handling**: Modified the combat system to ensure that, when combat is won, the enemy entity is disposed of, and the game returns to the main game screen. The player's stamina is also reset.
  - `CombatActions`: Updated to return the game from the combat screen to the main game, passing the enemy entity to dispose of it properly after combat.
  - `CombatExitDisplay`: Modified to trigger the appropriate win event with the enemy entity passed as an argument.
  - `CombatManager`: Updated to trigger the `combatWin` event with the enemy entity, ensuring proper clean-up after combat.

### CODE REVIEW

**Review by nownver — APPROVED** [review]
Looks good!

**Review by praneetdhoolia — APPROVED** [review]
Looks good to me!

**Review by praneetdhoolia — COMMENTED** [review]
StatManager seems to be throwing a java.lang.NullPointerException upon loading into game

**Comment by callumreillyy** [comment]
> StatManager seems to be throwing a java.lang.NullPointerException upon loading into game, please fix.

This happens once to initialise the endgameStats.json save file. Are you able to recreate it?

**Comment by phurinjeffy** [comment]
> StatManager seems to be throwing a java.lang.NullPointerException upon loading into game, please fix.

Yeah, I just made a fix for it. The cause for it is when you first run the game the 'saves/endgameStats.json' does not exist, so stats is reading from a null pointer. So I fixed it by making it initialise the file if it does not exist.

Thanks for pointing it out.

**Pull request merged**
