### PR TITLE
Minigame popup

### PR DESCRIPTION
**Pull request by 24msingh24**
# Description

This pull request introduces three new popups for each of the mini-games, providing a brief guide on how to play them. The popups are visible just before the every game starts and there is a help button during the game as well wherein player can click and learn a brief guide of game 

Fixes / Closes # (issue)
#609

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by PHONGNGYUEN1 — CHANGES_REQUESTED** [review]
Your tests is failing can u please fix them.

**Comment by PHONGNGYUEN1** [comment]
in the pop up here 
image
 is it possible to make the font thicker so its easier to read?

**Comment by EllaBerglas** [comment]
> in the pop up here image is it possible to make the font thicker so its easier to read?

Yeah Ichanged it already to be clearer, we have now jsut changed it again should be a bit better now.

**Review by PHONGNGYUEN1 — APPROVED** [review]

**Review by nreyana — APPROVED** [review]
Looks great!! The info/pop screen is good :)

**Pull request merged**
