### PR TITLE
1/player sprint3 cut scene

### PR DESCRIPTION
**Pull request by shaivikaaaa**
# Description

This pull request implements the CutSceneScreen class, which displays a cutscene in the game. The screen includes a background texture and a "Continue" button that transitions the player to the next screen (Animal Selection).
The new design layout for the screen is yet to be implemented and will be integrated in upcoming days.

Fixes / Closes # (issue)
#382 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
The testing is yet to be implemented 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by mitsudz — COMMENTED** [review]
What is this cutscene actually supposed to do? As of right now it just looks like we're unnecessarily adding in a new screen of a background which doesn't do anything.

**Comment by shaivikaaaa** [comment]
> What is this cutscene actually supposed to do? As of right now it just looks like we're unnecessarily adding in a new screen of a background which doesn't do anything.

The background image will be changed before this sprint ends only .. the other team member is working on it.
the use of this is it would help in to provide a short summary about the game mainly , like an overview.
Plus, for sprint 4 - we are planning to integrate animations into it - to make it more than just a screen .

**Review by jt-09 — APPROVED** [review]
Good modularity of code and good that you extended from screenadapter. Make sure there's ample testing for the cutscene screen since its  vital aspect of the storyline/game.

**Comment by shaivikaaaa** [comment]
> Good modularity of code and good that you extended from screenadapter. Make sure there's ample testing for the cutscene screen since its vital aspect of the storyline/game.

yes sure, thanks

**Pull request merged**
