### PR TITLE
Item Drop Upon Talking To Cows/Fish

### LINKED ISSUE #443: Team 4 & 3: Item dropping after talking to FNPC
# **Description**
**Task:** [Item dropping after talking to FNPC](#443)
**Feature:**  [Friendly NPC Interaction Update and Extensions](#326) 

This was the beginning of implementing item dropping after discussing with a Friendly NPC. Cows and Fish have been implemented. A cow drops a milk bucket 100% of the time and the fish drops sushi 60% of the time. These increase hunger and are extended from the existing food architecture
 
# **Dependencies**
Existing requirements are already implemented in terms of the AbstractFood class.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Generation of Food PNGs (Sep. 30)
- [x] Generation of Sushi and Milk classes (Sep. 30)
- [x] Integration with PauseTask using event triggers (Sep. 30)
- [x] Finalise unit testing (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- [Food Items](https://github.com/UQcsse3200/2024-studio-2/wiki/Food-Items)

# **Member**
- Bailey Stoodley (@BaileyS03 )
- Mittun Sudhahar (@mitsudz)

### PR DESCRIPTION
**Pull request by mitsudz**
# Description

There is a chance upon speaking to a cow/fish, that they will drop milk/sushi resp. These are food items which fill up a significant amount of health.

Fixes / Closes #443 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Functional testing for interacting with npcs. Unit testing added for underlying item objects.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by jakingy — COMMENTED** [review]
I'm wondering what the intended behaviour is when you repeatedly talk to the same NPC? As a test, I talked to a cow a bunch of times and the milk seems to spawn only some of the time, but the code for spawn probability only seems to affect whether the cow should spawn milk at all. Demonstration video attached.

https://github.com/user-attachments/assets/3a161635-bae5-464f-bbb9-2752a66e8579

**Comment by BaileyS03** [comment]
> I'm wondering what the intended behaviour is when you repeatedly talk to the same NPC? As a test, I talked to a cow a bunch of times and the milk seems to spawn only some of the time, but the code for spawn probability only seems to affect whether the cow should spawn milk at all. Demonstration video attached.
> 
>  AttackOnAnimal.2024-09-30.20-08-54.mp4

This is correct and will be refined with class input after friday.

**Review by jakingy — APPROVED** [review]
Feature works as intended.

**Review by shaivikaaaa — APPROVED** [review]
it looks fine to me.

**Pull request merged**
