### PR TITLE
6 start settings

### PR DESCRIPTION
**Pull request by jtayl647**
# Description

Added story elements
Added mini games UI components
Added mini-map features
Introduced chat bot implementation
Interactive owl on main menu
Added login features
UI Enhancements
Added animation of bird flying across main
In game time display

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by 27abdullah — COMMENTED** [review]
Wonderful!

**Review by davidaraba — APPROVED** [review]
Solid work and good to see unit tests.

**Review by Howard-12 — APPROVED** [review]
Mini map looks professional. I noticed the short delay when submitting login or register, also consider removing redundant stdout output. The rest looks good to me.

**Review by Jul-Wong — APPROVED** [review]

**Review by davidaraba — APPROVED** [review]
Great to see the hard work you've been putting in! Ensure testing sufficient. Nice job!

**Review by falgonn — APPROVED** [review]
looks good

**Pull request merged**
