### PR TITLE
Maze Mini-Game Entities and Game Mechanics

### PR DESCRIPTION
**Pull request by EllaBerglas**
# Description

This is the same pull request as https://github.com/UQcsse3200/2024-studio-2/pull/420 but had to be remade as the original one accientally closed.

This pull reqest implements all entities, health and combat, maze collisoin and AI path finding.
All entities inlcude:
- Angular fish
- Player fish
- Jelly Fish
- Eels
- Fish eggs
Eels and angular fish can chase the player. Jelly fish and angular fish can damage the player. Fish eggs are not interactable. Fish eggs collection, score and game termination is not in this pul request and will be completed by the end of sprint 3. Eels will have a stun affect that will also be impelmented in future pull request.

Fixes / Closes 
Part of Feature ticket #333 
Jelly fish #411
Fish eggs #368
Angular Fish #413
Path finidng #414
Eels #415
Health #416
maze collision detection #417
Player (animations and image) #419

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Visual tests
- [x] MazeCombatStatsComponentTest
- [x] MazePlayerFactoryTest
- [x] MazeTest
- [x] JellyfishTest 
- [x] ElectricEelsTest
- [x] AngularFishTest
- [x] FishEggTest
- [x] MazeObsticleTest
- [x] MazeNPCFactoryTest
Note that we will complete more comprehensive tests when feature is fully completed

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by jt-09 — APPROVED** [review]
Game looks really good! Great modularity of code and classes. Good to see ample unit testing

**Review by TarushiG — APPROVED** [review]
Love the new elements added! Great functionality & testing practices.

**Review by reemmi — APPROVED** [review]
Game looks really great! Testing is great and so is the documentation. Good job :)

**Review by nreyana — APPROVED** [review]
Looks really good!! yayyy good job!!

**Pull request merged**
