### PR TITLE
Maze Mini-Game Game Effects, Game Termination and score calculation

### PR DESCRIPTION
**Pull request by EllaBerglas**
# Description

This pull requests also makes changes to the attacks of entities and Implements a new version of a jelly fish as well as impletment particle effects to entities, including bubbles from the player and sparkles from the fish egg.

Fixes / Closes # (issue)
- [x] Score (#439)
- [x] Game termination (#442)
- [x] High score/ medal saving (#405)
- [x] JUnit testing (#371)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Visual Tests
- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lhick2108 — APPROVED** [review]
Gone through, looks pretty  good to me, no alarming issues. Test Cases are well done. If you merge in then I will change my PR to fix the merge conflict.

**Review by nreyana — APPROVED** [review]
Looks good, didn't spot any issues in the code. The new game is really cool

**Review by Jul-Wong — COMMENTED** [review]
Looks good! How far is the aggro range for the angler?

**Review by Jul-Wong — APPROVED** [review]

**Comment by EllaBerglas** [comment]
> Looks good! How far is the aggro range for the angler?

The entire thing. It's always chasing you

**Pull request merged**
